### ISSUE TITLE
Inclusion of Linear Haskell libraries

### ISSUE THREAD

**Issue by Kleidukos** [haskell/play-haskell#33]
### Feature request

There have been requests to have Linear Haskell libraries available in the Playground.

**Comment by tomsmeding** [comment]
Thanks, makes sense that this should be in there.

This took some sleuthing: https://github.com/haskell/play-haskell/compare/9978b6dcb58bd308e68eb5d29336c8a915b6b203...93f442199ba5238088265bf5a5252af8a943560c

Symptom was that building `text-2.0.2` failed because gcc couldn't find the `<string>` include, which is nonsense because the include file was there in the expected place. Turns out that gcc determines its include search path via heuristics (?) depending on where it finds _itself_, thus (since it's called as `/bin/gcc` by ghc) it matters whether `/bin` is a directory (like it was before my fixes) bound to `/bin` in the ubuntu base image, or a symlink to `/usr/bin` (as it indeed is in the base image). Hence the required changes in `mkbuildscript.sh`.
