### ISSUE TITLE
Is it possible to show the warning

### ISSUE THREAD

**Issue by jappeace** [haskell/play-haskell#38]
### Feature request

I was trying to figure out if it's possible to add a warning to just an instance of a typeclass
https://play.haskell.org/saved/4eguwdkk

however it appears af if the playground doesn't emit any warnings at all, I also added an unused module Data.Set and the playground doesn't emit this.

It'd be nice if it did this as well.

**Comment by tomsmeding** [comment]
> however it appears af if the playground doesn't emit any warnings at all, I also added an unused module Data.Set and the playground doesn't emit this.

This is resolved by putting `{-# OPTIONS -Wall #-}` at the top of your program. :)

I guess you're suggesting to enable `-Wall` by default. I'm not sure this is a good idea, though I _am_ a firm proponent of `-Wall`. I wonder what group would be good to poll on this.

Re your `WARNING` pragma: quoting from [the docs](https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/pragmas.html#warning-and-deprecated-pragmas) we find:

> Warnings and deprecations are not reported for (a) uses within the defining module, (b) defining a method in a class instance, and (c) uses in an export list. The latter reduces spurious complaints within a library in which one module gathers together and re-exports the exports of several others.

so this is expected behaviour.
